import './globals.css'
import Link from 'next/link'
import Sidebar from './(components)/Sidebar/Sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex h-screen flex-row justify-start">
          <Sidebar />
          <div className="bg-primary flex-1 p-4 text-black">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
